name: SpringAngularShop
services:
- dockerfile_path: frontend/Dockerfile
  git:
    branch: master
    repo_clone_url: https://github.com/sciabarrado/SpringBoot-Angular7-Online-Shopping-Store.git
    dockerfile_path:  
  name: frontend
